name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # 1. 确保 deno.json 包含 build 任务 & exports 字段
      - name: Fix deno.json
        run: |
          jq '.exports = "./main.ts" | .tasks.build = "deno compile --allow-net --allow-env --allow-read -o dist/z-ai2api-deno main.ts"' \
             deno.json > tmp.json && mv tmp.json deno.json

      - name: Build step
        run: deno task build

      # 2. 上传构建产物（可选，Deno Deploy 只认 entrypoint，不需要 dist）
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: dist/z-ai2api-deno

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "rsv51-zai2api-den-42"
          entrypoint: "main.ts"
          # 3. 正确 root 路径就是仓库根目录（默认值，直接删也行）
          root: "."
